# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ci-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: yarn
    - run: yarn --frozen-lockfile
    - run: yarn install-peers -f
    - run: yarn lint
    - run: yarn build
    - run: yarn test --coverage
      env:
        CI: true
    - name: Ensure GIT is clean after everything is done
      uses: numtide/clean-git-action@v1
